# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5b98be09c56fe7013b49561495156792a13a516cffb367a90ac1fc5e819b3c0f5607bf85f78644c548cbb0efdb71100a2a8a09b5de855c2bf14e3dee58e94a9

test:
  secret_key_base: 1b1f3c050c11d9338d366e86f32f115cb9445809c043b6f94bdbb28242de31ed19744aac720c2fa2d5b9bc2d635b6cf7720eb21254706f568e67010fa582e0cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
